services:
  - type: web
    name: satquery-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: MAPPLS_KEY
        value: blxdfrmzcqmrmwomxwfkbmarrnmxmwgbrgii
